export TERM="xterm-256color"

source ~/.antibody_bundles.txt

export VISUAL=nvim
export EDITOR="$VISUAL"

# Include exports
[[ -f ~/.exports ]] && source ~/.exports
# Include aliases
[[ -f ~/.aliases ]] && source ~/.aliases
# Include functions
[[ -f ~/.functions ]] && source ~/.functions
# Include secrets
[[ -f ~/.secrets ]] && source ~/.secrets
# Include fuzzy matching
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
set rtp+=/usr/local/opt/fzf

# Key bindings
bindkey -e
bindkey '^D'  delete-char
bindkey '\e\e[C' forward-word
bindkey '\e\e[D' backward-word

# Completion
autoload -U compinit
compinit

# History
bindkey -M isearch . self-insert # history search fix

# Powerline
function powerline_precmd() {
    PS1="$(~/go/bin/powerline-go -error $? -shell zsh)"
}

function install_powerline_precmd() {
  for s in "${precmd_functions[@]}"; do
    if [ "$s" = "powerline_precmd" ]; then
      return
    fi
  done
  precmd_functions+=(powerline_precmd)
}

if [ "$TERM" != "linux" ]; then
    install_powerline_precmd
fi

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh
