export ZSH=~/.oh-my-zsh

export TERM="xterm-256color"
ZSH_THEME="bullet-train"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git github zsh-syntax-highlighting vagrant virtualenv pip python brew osx)

BULLETTRAIN_PROMPT_ORDER=(
    git
    dir
)

BULLETTRAIN_GIT_PROMPT_CMD="\$(custom_git_prompt)"

custom_git_prompt() {
    prompt=$(git_prompt_info)
    prompt=${prompt//\//\ \ }
    prompt=${prompt//_/\ }
    echo ${prompt}
}

source $ZSH/oh-my-zsh.sh

# Include exports
[[ -f ~/.exports ]] && source ~/.exports
# Include aliases
[[ -f ~/.aliases ]] && source ~/.aliases
# Include functions
[[ -f ~/.functions ]] && source ~/.functions
# Include secrets
[[ -f ~/.secrets ]] && source ~/.secrets
# Include fuzzy matching
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Key bindings
bindkey -e
bindkey '^D'  delete-char
bindkey '\e\e[C' forward-word
bindkey '\e\e[D' backward-word

# Completion
fpath=(~/.completions $fpath)
setopt complete_aliases
autoload -U compinit
compinit
compctl -g '~/.teamocil/*(:t:r)' kickstart

# History
bindkey -M isearch . self-insert # history search fix
